theme: jekyll-theme-slate
title: Claudio Cicconetti
description: Homepage
show_downloads: false

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# Google Analytics
google_analytics: UA-141701891-1

plugins:
  - jekyll-avatar
